# ===========================================================================
# MT-Blogtimes: Shows your blog frequency as an image.
# A Plugin for Movable Type
#
# Release '0.1.0'
# February 03, 2005
#
#
# If you find the software useful or even like it, then a simple 'thank you'
# is always appreciated.  A reference back to me is even nicer.  If you find
# a way to make money from the software, do what you feel is right.
#
# Please have a look at the file 'AUTHORS' if you want to reach one of the
# authors by mail or if you want to make a donation.
#
# ===========================================================================
#
# Copyright (c) 2005, Nilesh Chaudhari and Daniel S. Haischt
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice, this
#      list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * The names of its contributors may not be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#    ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#    LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGE.
#
#
# ===========================================================================

package MTPlugins::MTBlogTimes::ServerImageMap;

# Perl Module Usages
use MTPlugins::MTBlogTimes::ObjectTemplate;

# Inheritance Declarations
@MTPlugins::MTBlogTimes::ServerImageMap::ISA = qw (MTPlugins::MTBlogTimes::ImageMap);

# Attribute Storage Object
attributes qw(basename location uri);

sub map {
    my $obj = shift;
    my $name = $obj->SUPER::name();
    my $basename = $obj->basename();
    
    # save the map to a file.
    &_save($basename, $name, &_map(\$obj));
}

sub _map {
    my $objref = $_[0];
    my $mapstr = "# Map generated by MT-BlogTimes.\n";
       $mapstr .= "# (C) 2005, Daniel S. Haischt\n#\nbase referer\n";
    
    foreach my $hotspot (@{$$objref->hotspots()}) {
        my $hotspot_hash_ref = $hotspot;
        my %hotspot_hash = %$hotspot_hash_ref;

        $mapstr .= $hotspot_hash{type} . " " . $hotspot_hash{uri} . " ";
        
        my $current_hotspots_ref = $hotspot_hash{coords};        
        my @current_hotspots = @$current_hotspots_ref;
        
        my @xa1 = split /\./, $current_hotspots[0];
        my $x1 = $xa1[0];
        my @ya1 = split /\./, $current_hotspots[1];
        my $y1 = $ya1[0];
        my @xa2 = split /\./, $current_hotspots[2];
        my $x2 = $xa2[0];
        my @ya2 = split /\./, $current_hotspots[3];
        my $y2 = $ya2[0];
        
        my $coords =  "$x1,$y1 $x2,$y2";

        $mapstr .= $coords . " \"" . $hotspot_hash{title} . "\"\n";
    }
    
    $mapstr .= "default nocontent";
    $mapstr;
}

sub _save {
    my ($basename, $name, $map) = @_;
    my ($nameref, $basenameref, $mapref);
    
    my $map_file = $basename . $name . ".map";

    open(MAP, "> $map_file")
        or die "Could not open $map_file for writing: $!\n";
    print MAP $map if $map or die "It does not make any sense to create an empty image map file.";    
    close(MAP);
}

1;
